spring.application.name=wtc-backend

# Conexão com o banco de dados MongoDB (usando o padrão local por enquanto)
spring.data.mongodb.uri=mongodb://localhost:27017/wtc_crm_db

# Chave secreta para criptografar o Token JWT (nunca compartilhe isso em produção)
api.security.token.secret=chave_secreta_wtc_challenge_2026
